# Generated by Django 6.0.7 on 2026-08-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
