# Generated by Django 6.0.7 on 2026-08-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.IntegerField(help_text='Discount percentage')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
